ASPFINAL/Controllers/AccountUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASPFINAL.Models;
using ASPFINAL.ViewModel;
using System.Web.Helpers;

namespace ASPFINAL.Controllers
{
    public class AccountUserController : Controller
    {
        AspFinalNewEntities db = new AspFinalNewEntities();

        public static User current_user;
        public static int user_id;
        // GET: AccountUser

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(string FullName, string Email, string Password)
        {
            //if (db.Users.Count(u => u.FullName == userrrs.FullName) == 1 || db.Users.Count(u => u.Email == userrrs.Email) == 1)
            //{
            //    ModelState.AddModelError("SameUser", "We already have a user with such username or email in our database.");
            //}
            //else
            //{
            //userrrs.Password = Crypto.HashPassword(userrrs.Password);
            Models.User user = new Models.User();
            user.FullName = FullName;
            user.Password = Crypto.HashPassword(Password);
            user.Email = Email;
            current_user = user;

            db.Users.Add(user);
            db.SaveChanges();


            Session["user2"] = user;
            Session["loguser"] = true;

            return RedirectToAction("Index", "Home");
            //}

            //return RedirectToAction("Index", "Home");
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User user)
        {
            if (db.Users.Count(u => u.Email == user.Email) == 1)
            {

                if (Crypto.VerifyHashedPassword(db.Users.First(u => u.Email == user.Email).Password, user.Password))
                {
                    current_user = db.Users.First(u => u.Email == user.Email);
                    Session["userLogged"] = true;
                    Session["user"] = db.Users.First(u => u.Email == user.Email);

                    return RedirectToAction("Index", "Home");

                }
                else
                {
                    ModelState.AddModelError("Loginerror", "Username  or  password is wrong");
                }

            }
            else
            {
                ModelState.AddModelError("Loginerror", "Username  or  password is wrong");

            }

            return View(user);

        }
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Users()
        {
            HomeindexView vm = new HomeindexView();
            vm.users = db.Users.ToList();
            return View(vm);
        }

    }

}

ASPFINAL/Views/AccountUser/Login.cshtml
@model ASPFINAL.Models.User
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    @*<div class="container-fluid" style="height:400px;display:block">
        <div class="row">
          
                    <div class="col-md-12">
                        @if (Session["userLogged"] == null)
                        {
                            <div class="login">

                                <form action="/AccountUser/Login" method="post">
                                    <div class="dropdown-menu">

                                        <div class="form-group" style="padding-left:2.5%">
                                            <label for="exampleDropdownFormEmail1">Email address *</label>
                                            <input type="text" name="Username" class="form-control" id="username" placeholder="Username" required="required">

                                        </div>
                                        <div class="form-group" style="padding-left:2.5%">
                                            <label for="exampleDropdownFormPassword1">Password  *</label>
                                            <input type="password" name="Password" class="form-control" id="password" placeholder="Password" required="required">


                                        </div>

                                        <button type="submit" class="btn btn-primary" value="Login" style="margin-left:2.5%">Sign in</button>


                                        <div class="dropdown-divider" style="border: none"></div>
                                        <a class="dropdown-item" href="@Url.Action("Register","AccountUser")">New around here? Sign up</a>
                                    </div>
                                    @Html.ValidationMessage("Loginerror", new { @class = "text-danger" })
                                </form>
                            </div>

                        }
                        else
                        {
                            <div class="txtuser">

                            </div>
                        }

                    </div>
                </div>
           
    </div>*@




<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
@if (Session["userLogged"] == null)
{
                <div class="panel-body">
                    <form   action="@Url.Action("Login","AccountUser")" method="post">
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="E-mail" name="Email" type="email" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" name="Password" type="password" >
                            </div>
                            
                            <a class="dropdown-item" href="@Url.Action("Register", "AccountUser")">New around here? Sign up</a>
                            <button type="submit" class="btn btn-primary" value="Login" style="margin-left:2.5%">Sign in</button>

                        </fieldset>
                    </form>
                </div>
}
            </div>
        </div>
    </div>
</div>

ASPFINAL/Views/AccountUser/Register.cshtml
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>


<body>
    <div class="container" style="padding-left:11%">
        <div class="contact-form ">

            <!-- Submition status -->
            <div id="form-messages"></div>

            <div class="container">
                <form action="@Url.Action("Register","AccountUser")" method="post">

                    <div class="row">

                        <div class="col-sm-10" style="text-align:center;">
                            <div class="form-group in_name ficon mt-30">
                                <span><i class="fas fa-signature" style="color:wheat"></i></span>
                                <input type="text" name="FullName" class="form-control" id="firstname" placeholder="Fullname" required="required" style="background-color: #1d2326;color:white">
                            </div>
                          
                            <div class="form-group in_email ficon">
                                <span><i class="fa fa-envelope" style="color:wheat"></i></span>
                                <input type="email" name="Email" class="form-control" id="email" placeholder="Email Address" required="required" style="background-color: #1d2326;color:white">
                            </div>
                            
                            <div class="form-group in_subject ficon">
                                <span><i class="fas fa-key" style="color:wheat"></i></span>
                                <input type="password" name="Password" class="form-control" id="password" placeholder="Password" required="required" style="background-color: #1d2326;color:white">
                            </div>
                          
                            <input type="submit" value="Register" />

                        </div>

                    </div>
                </form>

            </div>
        </div>
    </div>

</body>

</html>